Update demo docker-compose.yml & mailu.env with master
Mailu/infra pull request #21
Opened 2023-01-30 14:47 UTC by Diman0

Update demo docker-compose.yml & mailu.env with master

2023-01-30 15:57 UTC, nextgens requested changes

2023-01-30 15:57 UTC, nextgens commented on demo/docker-compose.yml
>        - $DNS
This needs to go; it's ona different network

2023-01-30 15:57 UTC, nextgens commented on demo/docker-compose.yml
>        - $DNS
This needs to go too

2023-01-31 08:09 UTC, Diman0 commented
I have tested it on the demo server. It all looks good and works well. I will merge the PR

2023-01-31 08:10 UTC, merged